
[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
size = 16.0

[window]
opacity = 0.75
blur = true
startup_mode = "Maximized"

[keyboard]
bindings = [
    { key = "ArrowRight", mods = "Command", action = "SelectNextTab" },
    { key = "ArrowLeft", mods = "Command", action = "SelectPreviousTab" },
]
